# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/misha-sh/course

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/misha-sh/course

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/misha-sh/course/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/misha-sh/course/CMakeFiles /home/misha-sh/course//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/misha-sh/course/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cars_sim

# Build rule for target.
cars_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cars_sim
.PHONY : cars_sim

# fast build rule for target.
cars_sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/build
.PHONY : cars_sim/fast

#=============================================================================
# Target rules for targets named cars_sim_autogen

# Build rule for target.
cars_sim_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cars_sim_autogen
.PHONY : cars_sim_autogen

# fast build rule for target.
cars_sim_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim_autogen.dir/build.make CMakeFiles/cars_sim_autogen.dir/build
.PHONY : cars_sim_autogen/fast

#=============================================================================
# Target rules for targets named range.v3.headers

# Build rule for target.
range.v3.headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 range.v3.headers
.PHONY : range.v3.headers

# fast build rule for target.
range.v3.headers/fast:
	$(MAKE) $(MAKESILENT) -f libs/range-v3/CMakeFiles/range.v3.headers.dir/build.make libs/range-v3/CMakeFiles/range.v3.headers.dir/build
.PHONY : range.v3.headers/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f libs/fmt/CMakeFiles/fmt.dir/build.make libs/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named fmt_autogen

# Build rule for target.
fmt_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt_autogen
.PHONY : fmt_autogen

# fast build rule for target.
fmt_autogen/fast:
	$(MAKE) $(MAKESILENT) -f libs/fmt/CMakeFiles/fmt_autogen.dir/build.make libs/fmt/CMakeFiles/fmt_autogen.dir/build
.PHONY : fmt_autogen/fast

cars_sim_autogen/mocs_compilation.o: cars_sim_autogen/mocs_compilation.cpp.o

.PHONY : cars_sim_autogen/mocs_compilation.o

# target to build an object file
cars_sim_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/cars_sim_autogen/mocs_compilation.cpp.o
.PHONY : cars_sim_autogen/mocs_compilation.cpp.o

cars_sim_autogen/mocs_compilation.i: cars_sim_autogen/mocs_compilation.cpp.i

.PHONY : cars_sim_autogen/mocs_compilation.i

# target to preprocess a source file
cars_sim_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/cars_sim_autogen/mocs_compilation.cpp.i
.PHONY : cars_sim_autogen/mocs_compilation.cpp.i

cars_sim_autogen/mocs_compilation.s: cars_sim_autogen/mocs_compilation.cpp.s

.PHONY : cars_sim_autogen/mocs_compilation.s

# target to generate assembly for a file
cars_sim_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/cars_sim_autogen/mocs_compilation.cpp.s
.PHONY : cars_sim_autogen/mocs_compilation.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/main/raster_map_builder.o: src/main/raster_map_builder.cpp.o

.PHONY : src/main/raster_map_builder.o

# target to build an object file
src/main/raster_map_builder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main/raster_map_builder.cpp.o
.PHONY : src/main/raster_map_builder.cpp.o

src/main/raster_map_builder.i: src/main/raster_map_builder.cpp.i

.PHONY : src/main/raster_map_builder.i

# target to preprocess a source file
src/main/raster_map_builder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main/raster_map_builder.cpp.i
.PHONY : src/main/raster_map_builder.cpp.i

src/main/raster_map_builder.s: src/main/raster_map_builder.cpp.s

.PHONY : src/main/raster_map_builder.s

# target to generate assembly for a file
src/main/raster_map_builder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main/raster_map_builder.cpp.s
.PHONY : src/main/raster_map_builder.cpp.s

src/main/simulator.o: src/main/simulator.cpp.o

.PHONY : src/main/simulator.o

# target to build an object file
src/main/simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main/simulator.cpp.o
.PHONY : src/main/simulator.cpp.o

src/main/simulator.i: src/main/simulator.cpp.i

.PHONY : src/main/simulator.i

# target to preprocess a source file
src/main/simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main/simulator.cpp.i
.PHONY : src/main/simulator.cpp.i

src/main/simulator.s: src/main/simulator.cpp.s

.PHONY : src/main/simulator.s

# target to generate assembly for a file
src/main/simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/main/simulator.cpp.s
.PHONY : src/main/simulator.cpp.s

src/projections/lon_lat_to_meters_projector.o: src/projections/lon_lat_to_meters_projector.cpp.o

.PHONY : src/projections/lon_lat_to_meters_projector.o

# target to build an object file
src/projections/lon_lat_to_meters_projector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/projections/lon_lat_to_meters_projector.cpp.o
.PHONY : src/projections/lon_lat_to_meters_projector.cpp.o

src/projections/lon_lat_to_meters_projector.i: src/projections/lon_lat_to_meters_projector.cpp.i

.PHONY : src/projections/lon_lat_to_meters_projector.i

# target to preprocess a source file
src/projections/lon_lat_to_meters_projector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/projections/lon_lat_to_meters_projector.cpp.i
.PHONY : src/projections/lon_lat_to_meters_projector.cpp.i

src/projections/lon_lat_to_meters_projector.s: src/projections/lon_lat_to_meters_projector.cpp.s

.PHONY : src/projections/lon_lat_to_meters_projector.s

# target to generate assembly for a file
src/projections/lon_lat_to_meters_projector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/projections/lon_lat_to_meters_projector.cpp.s
.PHONY : src/projections/lon_lat_to_meters_projector.cpp.s

src/projections/meters_to_image_projector.o: src/projections/meters_to_image_projector.cpp.o

.PHONY : src/projections/meters_to_image_projector.o

# target to build an object file
src/projections/meters_to_image_projector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/projections/meters_to_image_projector.cpp.o
.PHONY : src/projections/meters_to_image_projector.cpp.o

src/projections/meters_to_image_projector.i: src/projections/meters_to_image_projector.cpp.i

.PHONY : src/projections/meters_to_image_projector.i

# target to preprocess a source file
src/projections/meters_to_image_projector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/projections/meters_to_image_projector.cpp.i
.PHONY : src/projections/meters_to_image_projector.cpp.i

src/projections/meters_to_image_projector.s: src/projections/meters_to_image_projector.cpp.s

.PHONY : src/projections/meters_to_image_projector.s

# target to generate assembly for a file
src/projections/meters_to_image_projector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/projections/meters_to_image_projector.cpp.s
.PHONY : src/projections/meters_to_image_projector.cpp.s

src/rasterize/roads_map_reader.o: src/rasterize/roads_map_reader.cpp.o

.PHONY : src/rasterize/roads_map_reader.o

# target to build an object file
src/rasterize/roads_map_reader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_map_reader.cpp.o
.PHONY : src/rasterize/roads_map_reader.cpp.o

src/rasterize/roads_map_reader.i: src/rasterize/roads_map_reader.cpp.i

.PHONY : src/rasterize/roads_map_reader.i

# target to preprocess a source file
src/rasterize/roads_map_reader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_map_reader.cpp.i
.PHONY : src/rasterize/roads_map_reader.cpp.i

src/rasterize/roads_map_reader.s: src/rasterize/roads_map_reader.cpp.s

.PHONY : src/rasterize/roads_map_reader.s

# target to generate assembly for a file
src/rasterize/roads_map_reader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_map_reader.cpp.s
.PHONY : src/rasterize/roads_map_reader.cpp.s

src/rasterize/roads_rasterizer.o: src/rasterize/roads_rasterizer.cpp.o

.PHONY : src/rasterize/roads_rasterizer.o

# target to build an object file
src/rasterize/roads_rasterizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer.cpp.o
.PHONY : src/rasterize/roads_rasterizer.cpp.o

src/rasterize/roads_rasterizer.i: src/rasterize/roads_rasterizer.cpp.i

.PHONY : src/rasterize/roads_rasterizer.i

# target to preprocess a source file
src/rasterize/roads_rasterizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer.cpp.i
.PHONY : src/rasterize/roads_rasterizer.cpp.i

src/rasterize/roads_rasterizer.s: src/rasterize/roads_rasterizer.cpp.s

.PHONY : src/rasterize/roads_rasterizer.s

# target to generate assembly for a file
src/rasterize/roads_rasterizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer.cpp.s
.PHONY : src/rasterize/roads_rasterizer.cpp.s

src/rasterize/roads_rasterizer_deprecated.o: src/rasterize/roads_rasterizer_deprecated.cpp.o

.PHONY : src/rasterize/roads_rasterizer_deprecated.o

# target to build an object file
src/rasterize/roads_rasterizer_deprecated.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_deprecated.cpp.o
.PHONY : src/rasterize/roads_rasterizer_deprecated.cpp.o

src/rasterize/roads_rasterizer_deprecated.i: src/rasterize/roads_rasterizer_deprecated.cpp.i

.PHONY : src/rasterize/roads_rasterizer_deprecated.i

# target to preprocess a source file
src/rasterize/roads_rasterizer_deprecated.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_deprecated.cpp.i
.PHONY : src/rasterize/roads_rasterizer_deprecated.cpp.i

src/rasterize/roads_rasterizer_deprecated.s: src/rasterize/roads_rasterizer_deprecated.cpp.s

.PHONY : src/rasterize/roads_rasterizer_deprecated.s

# target to generate assembly for a file
src/rasterize/roads_rasterizer_deprecated.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_deprecated.cpp.s
.PHONY : src/rasterize/roads_rasterizer_deprecated.cpp.s

src/rasterize/roads_rasterizer_handler.o: src/rasterize/roads_rasterizer_handler.cpp.o

.PHONY : src/rasterize/roads_rasterizer_handler.o

# target to build an object file
src/rasterize/roads_rasterizer_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_handler.cpp.o
.PHONY : src/rasterize/roads_rasterizer_handler.cpp.o

src/rasterize/roads_rasterizer_handler.i: src/rasterize/roads_rasterizer_handler.cpp.i

.PHONY : src/rasterize/roads_rasterizer_handler.i

# target to preprocess a source file
src/rasterize/roads_rasterizer_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_handler.cpp.i
.PHONY : src/rasterize/roads_rasterizer_handler.cpp.i

src/rasterize/roads_rasterizer_handler.s: src/rasterize/roads_rasterizer_handler.cpp.s

.PHONY : src/rasterize/roads_rasterizer_handler.s

# target to generate assembly for a file
src/rasterize/roads_rasterizer_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_handler.cpp.s
.PHONY : src/rasterize/roads_rasterizer_handler.cpp.s

src/rasterize/roads_rasterizer_segmenter.o: src/rasterize/roads_rasterizer_segmenter.cpp.o

.PHONY : src/rasterize/roads_rasterizer_segmenter.o

# target to build an object file
src/rasterize/roads_rasterizer_segmenter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_segmenter.cpp.o
.PHONY : src/rasterize/roads_rasterizer_segmenter.cpp.o

src/rasterize/roads_rasterizer_segmenter.i: src/rasterize/roads_rasterizer_segmenter.cpp.i

.PHONY : src/rasterize/roads_rasterizer_segmenter.i

# target to preprocess a source file
src/rasterize/roads_rasterizer_segmenter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_segmenter.cpp.i
.PHONY : src/rasterize/roads_rasterizer_segmenter.cpp.i

src/rasterize/roads_rasterizer_segmenter.s: src/rasterize/roads_rasterizer_segmenter.cpp.s

.PHONY : src/rasterize/roads_rasterizer_segmenter.s

# target to generate assembly for a file
src/rasterize/roads_rasterizer_segmenter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/rasterize/roads_rasterizer_segmenter.cpp.s
.PHONY : src/rasterize/roads_rasterizer_segmenter.cpp.s

src/ui/main_window.o: src/ui/main_window.cpp.o

.PHONY : src/ui/main_window.o

# target to build an object file
src/ui/main_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/main_window.cpp.o
.PHONY : src/ui/main_window.cpp.o

src/ui/main_window.i: src/ui/main_window.cpp.i

.PHONY : src/ui/main_window.i

# target to preprocess a source file
src/ui/main_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/main_window.cpp.i
.PHONY : src/ui/main_window.cpp.i

src/ui/main_window.s: src/ui/main_window.cpp.s

.PHONY : src/ui/main_window.s

# target to generate assembly for a file
src/ui/main_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/main_window.cpp.s
.PHONY : src/ui/main_window.cpp.s

src/ui/map/glmapwidget.o: src/ui/map/glmapwidget.cpp.o

.PHONY : src/ui/map/glmapwidget.o

# target to build an object file
src/ui/map/glmapwidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/map/glmapwidget.cpp.o
.PHONY : src/ui/map/glmapwidget.cpp.o

src/ui/map/glmapwidget.i: src/ui/map/glmapwidget.cpp.i

.PHONY : src/ui/map/glmapwidget.i

# target to preprocess a source file
src/ui/map/glmapwidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/map/glmapwidget.cpp.i
.PHONY : src/ui/map/glmapwidget.cpp.i

src/ui/map/glmapwidget.s: src/ui/map/glmapwidget.cpp.s

.PHONY : src/ui/map/glmapwidget.s

# target to generate assembly for a file
src/ui/map/glmapwidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/map/glmapwidget.cpp.s
.PHONY : src/ui/map/glmapwidget.cpp.s

src/ui/map/map_painter.o: src/ui/map/map_painter.cpp.o

.PHONY : src/ui/map/map_painter.o

# target to build an object file
src/ui/map/map_painter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/map/map_painter.cpp.o
.PHONY : src/ui/map/map_painter.cpp.o

src/ui/map/map_painter.i: src/ui/map/map_painter.cpp.i

.PHONY : src/ui/map/map_painter.i

# target to preprocess a source file
src/ui/map/map_painter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/map/map_painter.cpp.i
.PHONY : src/ui/map/map_painter.cpp.i

src/ui/map/map_painter.s: src/ui/map/map_painter.cpp.s

.PHONY : src/ui/map/map_painter.s

# target to generate assembly for a file
src/ui/map/map_painter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cars_sim.dir/build.make CMakeFiles/cars_sim.dir/src/ui/map/map_painter.cpp.s
.PHONY : src/ui/map/map_painter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... cars_sim_autogen"
	@echo "... fmt_autogen"
	@echo "... range.v3.headers"
	@echo "... cars_sim"
	@echo "... fmt"
	@echo "... cars_sim_autogen/mocs_compilation.o"
	@echo "... cars_sim_autogen/mocs_compilation.i"
	@echo "... cars_sim_autogen/mocs_compilation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/main/raster_map_builder.o"
	@echo "... src/main/raster_map_builder.i"
	@echo "... src/main/raster_map_builder.s"
	@echo "... src/main/simulator.o"
	@echo "... src/main/simulator.i"
	@echo "... src/main/simulator.s"
	@echo "... src/projections/lon_lat_to_meters_projector.o"
	@echo "... src/projections/lon_lat_to_meters_projector.i"
	@echo "... src/projections/lon_lat_to_meters_projector.s"
	@echo "... src/projections/meters_to_image_projector.o"
	@echo "... src/projections/meters_to_image_projector.i"
	@echo "... src/projections/meters_to_image_projector.s"
	@echo "... src/rasterize/roads_map_reader.o"
	@echo "... src/rasterize/roads_map_reader.i"
	@echo "... src/rasterize/roads_map_reader.s"
	@echo "... src/rasterize/roads_rasterizer.o"
	@echo "... src/rasterize/roads_rasterizer.i"
	@echo "... src/rasterize/roads_rasterizer.s"
	@echo "... src/rasterize/roads_rasterizer_deprecated.o"
	@echo "... src/rasterize/roads_rasterizer_deprecated.i"
	@echo "... src/rasterize/roads_rasterizer_deprecated.s"
	@echo "... src/rasterize/roads_rasterizer_handler.o"
	@echo "... src/rasterize/roads_rasterizer_handler.i"
	@echo "... src/rasterize/roads_rasterizer_handler.s"
	@echo "... src/rasterize/roads_rasterizer_segmenter.o"
	@echo "... src/rasterize/roads_rasterizer_segmenter.i"
	@echo "... src/rasterize/roads_rasterizer_segmenter.s"
	@echo "... src/ui/main_window.o"
	@echo "... src/ui/main_window.i"
	@echo "... src/ui/main_window.s"
	@echo "... src/ui/map/glmapwidget.o"
	@echo "... src/ui/map/glmapwidget.i"
	@echo "... src/ui/map/glmapwidget.s"
	@echo "... src/ui/map/map_painter.o"
	@echo "... src/ui/map/map_painter.i"
	@echo "... src/ui/map/map_painter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

